//Authentication
export const LOGINSUCCESS = 'LOGINSUCCESS';
export const LOGINFAIL = 'LOGINFAIL';
export const REGISTERSUCCESS = 'REGISTERSUCCESS';
export const REGISTERFAIL = 'REGISTERFAIL';
export const LOGOUT = 'LOGOUT';
export const LOADUSER = 'LOADUSER';

//Event
export const EVENTCREATESUCCESS = 'EVENTCREATESUCCESS';
export const EVENTDELETESUCCESS = 'EVENTDELETESUCCESS';
export const EVENTUPDATESUCCESS = 'EVENTUPDATESUCCESS';
export const LOADEVENT = 'LOADEVENT';
